// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusError    StatusResponseStatus = "error"
	StatusResponseStatusRunning  StatusResponseStatus = "running"
	StatusResponseStatusStarting StatusResponseStatus = "starting"
	StatusResponseStatusStopping StatusResponseStatus = "stopping"
)

// AdminDeployRequest defines model for AdminDeployRequest.
type AdminDeployRequest struct {
	// Category The category of the challenge to deploy.
	Category string `json:"category"`

	// ChallengeName The name of the challenge to deploy.
	ChallengeName string `json:"challenge_name"`
}

// BulkOperationResponse defines model for BulkOperationResponse.
type BulkOperationResponse struct {
	Challenges      []ChallengeCategoryResponse `json:"challenges"`
	ChallengesCount int                         `json:"challenges_count"`
	Message         string                      `json:"message"`
}

// ChallengeCategoryResponse defines model for ChallengeCategoryResponse.
type ChallengeCategoryResponse struct {
	Category      string `json:"category"`
	ChallengeName string `json:"challenge_name"`
}

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	// Category The category of the challenge to deploy.
	Category string `json:"category"`

	// ChallengeName The name of the challenge to deploy.
	ChallengeName string `json:"challenge_name"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ConnectionInfo *string    `json:"connection_info,omitempty"`
	ExpirationTime *time.Time `json:"expiration_time,omitempty"`

	// ExtensionTime Time duration each extension adds (e.g., "30m", "1h").
	ExtensionTime *string `json:"extension_time,omitempty"`

	// ExtensionsLeft Number of extensions left for this deployment. -1 if unlimited.
	ExtensionsLeft *int                  `json:"extensions_left,omitempty"`
	Status         *StatusResponseStatus `json:"status,omitempty"`

	// Unique Whether this is a unique deployment or not.
	Unique *bool `json:"unique,omitempty"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// DeployAdminInstanceJSONRequestBody defines body for DeployAdminInstance for application/json ContentType.
type DeployAdminInstanceJSONRequestBody = AdminDeployRequest

// TerminateAdminInstanceJSONRequestBody defines body for TerminateAdminInstance for application/json ContentType.
type TerminateAdminInstanceJSONRequestBody = AdminDeployRequest

// DeployInstanceJSONRequestBody defines body for DeployInstance for application/json ContentType.
type DeployInstanceJSONRequestBody = DeployRequest

// TerminateInstanceJSONRequestBody defines body for TerminateInstance for application/json ContentType.
type TerminateInstanceJSONRequestBody = DeployRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check communication with Zync
	// (POST /admin/config-check)
	ConfigCheck(ctx echo.Context) error
	// Deploy a unique challenge (admin only)
	// (POST /admin/deploy)
	DeployAdminInstance(ctx echo.Context) error
	// Deploy all unique challenges (admin only)
	// (POST /admin/deploy-all)
	DeployAllAdminInstances(ctx echo.Context) error
	// List all unique challenges
	// (GET /admin/list-unique-challs)
	ListUniqueChallenges(ctx echo.Context) error
	// Reload challenges index
	// (POST /admin/reload-challs)
	ReloadChallenges(ctx echo.Context) error
	// Terminate a unique challenge (admin only)
	// (POST /admin/terminate)
	TerminateAdminInstance(ctx echo.Context) error
	// Terminate all unique challenges (admin only)
	// (POST /admin/terminate-all)
	TerminateAllAdminInstances(ctx echo.Context) error
	// Deploy a challenge instance
	// (POST /deploy)
	DeployInstance(ctx echo.Context) error
	// Extend the duration of a deployment
	// (POST /extend)
	ExtendInstance(ctx echo.Context) error
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Get deployment status
	// (GET /status)
	GetInstanceStatus(ctx echo.Context) error
	// Terminate a challenge instance
	// (POST /terminate)
	TerminateInstance(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ConfigCheck converts echo context to params.
func (w *ServerInterfaceWrapper) ConfigCheck(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfigCheck(ctx)
	return err
}

// DeployAdminInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeployAdminInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployAdminInstance(ctx)
	return err
}

// DeployAllAdminInstances converts echo context to params.
func (w *ServerInterfaceWrapper) DeployAllAdminInstances(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployAllAdminInstances(ctx)
	return err
}

// ListUniqueChallenges converts echo context to params.
func (w *ServerInterfaceWrapper) ListUniqueChallenges(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUniqueChallenges(ctx)
	return err
}

// ReloadChallenges converts echo context to params.
func (w *ServerInterfaceWrapper) ReloadChallenges(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReloadChallenges(ctx)
	return err
}

// TerminateAdminInstance converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateAdminInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateAdminInstance(ctx)
	return err
}

// TerminateAllAdminInstances converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateAllAdminInstances(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateAllAdminInstances(ctx)
	return err
}

// DeployInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeployInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployInstance(ctx)
	return err
}

// ExtendInstance converts echo context to params.
func (w *ServerInterfaceWrapper) ExtendInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExtendInstance(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceStatus(ctx)
	return err
}

// TerminateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateInstance(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/admin/config-check", wrapper.ConfigCheck)
	router.POST(baseURL+"/admin/deploy", wrapper.DeployAdminInstance)
	router.POST(baseURL+"/admin/deploy-all", wrapper.DeployAllAdminInstances)
	router.GET(baseURL+"/admin/list-unique-challs", wrapper.ListUniqueChallenges)
	router.POST(baseURL+"/admin/reload-challs", wrapper.ReloadChallenges)
	router.POST(baseURL+"/admin/terminate", wrapper.TerminateAdminInstance)
	router.POST(baseURL+"/admin/terminate-all", wrapper.TerminateAllAdminInstances)
	router.POST(baseURL+"/deploy", wrapper.DeployInstance)
	router.POST(baseURL+"/extend", wrapper.ExtendInstance)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/status", wrapper.GetInstanceStatus)
	router.POST(baseURL+"/terminate", wrapper.TerminateInstance)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/cNhD9KwO2hwTYL8fuoXtz1knqomiLxEGAJoZBS6MVY4pUyJFjJdj/XpCUVlqL",
	"6w/UTuygN+1qOJx573FmxK8s0UWpFSqybP6V2STHgvvH/bQQ6gBLqevX+KlCS+7f0ugSDQn0NgknXGpT",
	"u+cUbWJESUIrNmdHOUL7FnQG5H7nXEpUSwTSkHrPEzZiVJfI5sySEWrJViO2tjtRvMC4b/fmdn5XI2bw",
	"UyUMpmz+vgt9sN/xeqk+/YgJuZCeV/LsrxINdyG8RltqZTGCR+vJ/xKEhX/42WDG5uynaQf2tEF6umiX",
	"LJqA1t5X6zi4MbzeQMaeJLpSnpHGRijCJRpnVaC1fIm9l1swaA0jjvt/RRHZHveVKrkB2XfJ2//6DTi8",
	"MEabYf5XKmXg5A1xquwVPGulMHFJngiV6SjdeFGKcIpOSARwMm0KTmzOUk449v+OYgsJle2vuwSqKBDS",
	"KvgG5EkO6yXA09TCE5wsJyP4wHZnxQfmHnbyD+zp5Mrd7InEjIbb/VkVp2gcg50pOFPItAHKhW2YLFDR",
	"BMY7IDKolBSFIEx7e/bOrfX4ur1QVYUj2VRKuYjcO12W7SM3FB7R03ocSaBS4lMVgeldjpRjE6GwwCFY",
	"9qIFbUBp6sV4qrVErmKqcGFjUhlB9RtX0YISTpEbNPsV5d2vly3Nv787cll4a+fcv+02y4lKtnKOWxFt",
	"ZrD/96HHOAQs1BIWRy+7M2Shsu7PfWXFqfRSEiSd41dcnnMlviAcKktcJX7XczQ2OJ5Nnk12HHa6RMVL",
	"weZsdzKb7LIRKznlPrEpd11xmmiVieU4yTE58+dAh+qi2xZxmLI5W3irhTdyhzecG+/n2Ww2zGyhi6JS",
	"IgkS/iwoh39qlYCtkgStzSrpotub7QyXvlW8olwb8QXTYLQ7NHqpzalIU1QwBt/dgXvHsK4rqxH7JRbZ",
	"oSI0ikuwaM7RQNBdn3w2f79J+/vj1fGI2aoouKuvzMMASTxF76rBNvC6HdVQ0n38LY8slEa09FyndVOK",
	"CEN/5GUpmw2nH61Lpx1zrmvNkQlotVmGyVS4GlD7bAjgQXe6mkg99iW1dEVBP+dSpNDsDVN4q86U/qxg",
	"3Xvh8OAbSGJv9uuVGXFpkKc14IWwZHsiuhMWXjRaW43uXpQhia4Idp34iRcjaCXrp0N1jrmU1ypUyg2R",
	"WhYXyp2AFJ9PI6A5w36t982kpflRFpaWQykHLNqtNEphaRzMx97cM7LECJt/CEtvveWim4jj5fzGVN71",
	"l8GQZxe1m04GkDxipn1OUZ771BqUmqc9VttDuhnPa2/W14pQKV5AZnQBqbBnwFUKVemGUj+lC1Vg4b4G",
	"vB0bXZJJ8HetRKJB/BANfgugfWoITSEUJ9xeO49ak4fc4CMAtnG7seab0rk324t8neh+jc90pe6V+jVp",
	"t+mkazFc3Uw7QVzfT2ffqZ9Sn/xH31B7bN6wp95sZL/nw/wDDeo3G7eFgtLopUFrPR4SCR/l8N3VCtFK",
	"xMvK36yk22X1wr/fkNU9lYNLN18RPA7WN08+KOw3dVlvlc6CK6WpWdSv2U9Ia0BuZD2Cgl/0b5kM8iTH",
	"dARIyeTpLWR1XaO4z6ISuPKD1PqSTmfAN7Z3pOfIZbg2ik7jr5B+Cxb/ke7Nq8vu6u3ae9Ah92/QnIsE",
	"QVgI0deXsdmAIsQP4fLI59ztvi3nVuRBiN9X6sECDJIReH6rVncLBT748vUK6dKHtGPG83mbOffhdcW7",
	"n26/xdwZbSKr1b8BAAD//2fzFhrhHAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
