// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusError    StatusResponseStatus = "error"
	StatusResponseStatusRunning  StatusResponseStatus = "running"
	StatusResponseStatusStarting StatusResponseStatus = "starting"
	StatusResponseStatusStopping StatusResponseStatus = "stopping"
)

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	// ChallengeName The name of the challenge to deploy.
	ChallengeName string `json:"challenge_name"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ConnectionInfo *string               `json:"connection_info,omitempty"`
	Status         *StatusResponseStatus `json:"status,omitempty"`
	Uptime         *string               `json:"uptime,omitempty"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// DeployInstanceJSONRequestBody defines body for DeployInstance for application/json ContentType.
type DeployInstanceJSONRequestBody = DeployRequest

// TerminateInstanceJSONRequestBody defines body for TerminateInstance for application/json ContentType.
type TerminateInstanceJSONRequestBody = DeployRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Deploy a challenge instance
	// (POST /deploy)
	DeployInstance(ctx echo.Context) error
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Get deployment status
	// (GET /status)
	GetInstanceStatus(ctx echo.Context) error
	// Terminate a challenge instance
	// (POST /terminate)
	TerminateInstance(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeployInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeployInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeployInstance(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceStatus(ctx)
	return err
}

// TerminateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) TerminateInstance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TerminateInstance(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/deploy", wrapper.DeployInstance)
	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/status", wrapper.GetInstanceStatus)
	router.POST(baseURL+"/terminate", wrapper.TerminateInstance)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUTVPjOBD9K6rePaaSAMthfWNhYTKnKQg1BypFCbkTC2xJtNqZylD+71OS7ITEgWEY",
	"DnOT3V+vX7/uJ1C2ctagYQ/ZE3hVYCXj8wxdaVeX+Fij5/DDkXVIrDGaVSHLEs0Cb42sMPzJ0SvSjrU1",
	"kMG0QBEsws4FFyjW/oKtyGPuIQyAVw4hA8+kzQKaZgCEj7UmzCG72S0yW/vbu3tUDM0A/iey1IdXofdy",
	"EXH1S/SSXLHk2l+id9Z43NOsNQZV6OxWm7ndk3UAPuYIJjR1FdBTbUwwBpt1rntK4vTECH026OeqHevq",
	"beBDZVQ1aV5dheElwHcoCemk5mLzdW6pkgwZfP46DUCiN2StdTOLgtlBExJ3vW5P9uTLRMwttUPUZiFO",
	"p+eb+fo4Vs1lyBUsp+vJT4xnaVQstkTyKd/B8HA4Dl1bh0Y6DRkcDcfDIxiAk1zEfkapWJyMTXIM85EB",
	"0iSHrFVrVwCSjNDzfzZftRNkNDFQOldqFUNH9z5A6HQfXn8TziGDv0abxRi1WzHaXolmW61MNcYfSUQR",
	"9uH4sM9fylKhYdGCFFIpdIx5YOGf8bgfMzFLWepctLXFSFybB2O/mefsnqXwg374tZE1F5b0967Gv6/i",
	"kiWhzFdCG+HILgi9j3yUyBjijxPGDyE1LXAkc7dnRjKyFB5piSSwddwIHrKbbanfzJrZAHxdVZJW65aE",
	"fHZ9dCeRkGhUoCzTjixwj6oukD8lj95gf42A7XOyORU/X+8eLVdIS61QaC8S+tUuJ1sUJPxCFageUs+b",
	"6i/13K1ROou/2/trw985vPvajR6CkEnjspPvGzR+vH+PWk29Q0wXyO3NizvS0hgpZaRKG8n48oGadi5/",
	"3o3aw1OHVlsjfK0Uej+vyw/i/v37vCbxpZVumh8BAAD//0e+AlDSCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
